printWidth: 110
tabWidth: 4
useTabs: true
semi: true
singleQuote: true
quoteProps: 'consistent'
jsxSingleQuote: false
trailingComma: 'es5'
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: 'avoid'
